[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.33"
evm_version = "osaka"
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@circuits/target/=../circuits/target/",
]
gas_reports = []
optimizer = true
optimizer_runs = 999999
via_ir = false

[rpc_endpoints]
sepolia = "${SEPOLIA_URL}"
mainnet = "${MAINNET_URL}"
local = "http://${ANVIL_HOST}:${ANVIL_PORT}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 120
tab_width = 2
bracket_spacing = true
int_types = "long"
number_underscore = "thousands"
sort_imports = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
