[package]
name = "circuits"
type = "bin"
authors = ["m374-crypt0"]
compiler_version = "1.0.0"
description = "evaluates RWA policy eligibility"
entry = "src/main.nr"
license = "MIT"

[dependencies]
poseidon = { tag = "v0.2.3", git = "https://github.com/noir-lang/poseidon" }
